### ISSUE TITLE
USER STORY: Save Posts

### ISSUE THREAD

**Issue by annieross10** [annieross10/blink-box#12]
As a **user**, I want to be able to **save posts posted by other users**

**Assessment Criteria**

- Users should have the ability to save posts.
- Each photo should display the total number of saved posts by users but not display the name of the user.
- Users should be prevented from saving the same photo multiple times.
- Saved photos should visually indicate the user's action, such as changing the appearance of the save button.
- Saved photos should be stored in a user's profile for future reference.

**Tasks**

- [ ] Implement functionality allowing users to save photos with a single click or tap.
- [ ] Display the total number of saved for each photo in the community feed but not display the users name.
- [ ] Implement mechanisms to prevent users from saving the same photo multiple times.
- [ ] Change the appearance of the save button when a user has saved the photo.
- [ ] Develop a feature to store saved photos in a user's profile for future reference.
- [ ] Test the functionality.
