### ISSUE TITLE
USER STORY: Make friends with other users

### ISSUE THREAD

**Issue by annieross10** [annieross10/blink-box#8]
As a **user** I want to be able to **follow other users, so I can see their posts in my feed.**

**Acceptance Criteria:**

- Users should have the option to add other users as friends.
- Users should have an accept or decline option for friend requests.
- When a user is friends with another user, posts from the user should appear in the feed.
- Users should be able to view a list of users they are currently friends with.
- The following functionality should be intuitive and easily accessible within the user interface.
- Notifications should be sent to users when they gain new friend requests or when other users they are friends with make new posts.

**Tasks**

- [ ] Implement Freind Request Functionality.
- [ ] Implement buttons or icons to represent friend request actions.
- [ ] Update Feed with friends Posts. 
- [ ] Display list of friends in user profile. 
- [ ] Test functionality
